# Generated by Django 3.1.6 on 2021-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20210219_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stageNum',
            field=models.IntegerField(default=0),
        ),
    ]
