# Generated by Django 3.1.6 on 2021-02-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_stagenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect', models.BooleanField(default=True, verbose_name='見込み')),
                ('introduction', models.BooleanField(default=False, verbose_name='物件紹介')),
                ('opportunity', models.BooleanField(default=False, verbose_name='商談')),
                ('closing', models.BooleanField(default=False, verbose_name='クロージング')),
                ('onHold', models.BooleanField(default=False, verbose_name='申込み')),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='stageNum',
        ),
        migrations.AddField(
            model_name='lead',
            name='step',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.step'),
            preserve_default=False,
        ),
    ]
