# Generated by Django 3.1.6 on 2021-02-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20210221_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='step',
        ),
    ]
