# Generated by Django 3.1.6 on 2021-02-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_remove_lead_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='step',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.step'),
        ),
    ]
