# Generated by Django 3.1.6 on 2021-02-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_delete_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('suspect', 'suspect'), ('introduction', 'introduction'), ('opportunity', 'opportunity'), ('closing', 'closing')], default='suspect', max_length=20),
        ),
    ]
