# Generated by Django 3.1.6 on 2021-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20210303_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(choices=[('住居（賃貸）', '住居（賃貸）'), ('住居（テナント）', '住居（テナント）'), ('売買', '売買'), ('修繕', '修繕'), ('保険', '保険')], max_length=20),
        ),
    ]
