# Generated by Django 3.1.6 on 2021-03-11 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0017_auto_20210310_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(choices=[('住居（賃貸）', '住居（賃貸）'), ('住居（テナント）', '住居（テナント）'), ('売買', '売買'), ('修繕', '修繕'), ('保険', '保険')], max_length=20, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=100, verbose_name='リード名'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.person', verbose_name='担当者名'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('suspect', 'suspect'), ('introduction', 'introduction'), ('opportunity', 'opportunity'), ('closing', 'closing')], default='suspect', max_length=20, verbose_name='ステージ'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
