# Generated by Django 3.1.6 on 2021-03-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20210311_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(choices=[('住居（賃貸）', '住居（賃貸）'), ('住居（テナント）', '住居（テナント）'), ('売買', '売買'), ('修繕', '修繕'), ('保険', '保険')], default='住居（賃貸）', max_length=20, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
