# Generated by Django 3.1.6 on 2021-02-16 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prefecture', models.CharField(default='神奈川県', max_length=10)),
                ('city', models.CharField(default='横浜市都筑区', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('bicycle_parking', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('payment', models.IntegerField(default=0)),
                ('maintenance_fee', models.IntegerField(default=0)),
                ('deposit', models.IntegerField(default=0)),
                ('key_money', models.IntegerField(default=0)),
                ('zumen', models.FileField(upload_to='zumen')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.propertymodel')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(max_length=50)),
                ('img_path', models.ImageField(upload_to='img/')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.rent')),
            ],
        ),
    ]
