# Generated by Django 3.1.6 on 2021-02-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='zumen',
            field=models.FileField(blank=True, null=True, upload_to='zumen'),
        ),
    ]
