# Generated by Django 3.1.6 on 2021-02-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_auto_20210216_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
