# Generated by Django 3.1.6 on 2021-02-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_auto_20210216_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymodel',
            old_name='address',
            new_name='branch_number',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='deposit',
            new_name='common_fee',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='maintenance_fee',
            new_name='gurantee_deposit',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='payment',
            new_name='management_fee',
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='city_eng',
            field=models.CharField(default='nakamachidai Tsuzuki-ku Yokohama-shi', max_length=100),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='closest_station',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='closest_train',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='date_of_construction',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='walking_from_station',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rent',
            name='floor_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='footprint',
            field=models.IntegerField(blank=True, null=True, verbose_name='㎡数'),
        ),
        migrations.AddField(
            model_name='rent',
            name='insurance_fee',
            field=models.IntegerField(default=18000),
        ),
        migrations.AddField(
            model_name='rent',
            name='renewal_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rent',
            name='rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rent',
            name='sec_deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='city',
            field=models.CharField(default='横浜市都筑区仲町台', max_length=100),
        ),
    ]
