# Generated by Django 3.1.6 on 2021-02-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_propertymodel_title_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
