# Generated by Django 3.1.6 on 2021-03-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_rent_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='city_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
