# Generated by Django 3.1.6 on 2021-03-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_auto_20210303_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='available',
            new_name='vacancy',
        ),
    ]
