# Generated by Django 3.1.6 on 2021-03-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_auto_20210303_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='zumen',
            field=models.FileField(blank=True, null=True, upload_to='media/zumen'),
        ),
    ]
