# Generated by Django 3.1 on 2021-02-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyImgs',
            new_name='PropertyImg',
        ),
    ]
