# Generated by Django 3.1 on 2021-02-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20210215_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimg',
            name='img_path',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='zumen',
            field=models.FileField(upload_to='zumen'),
        ),
    ]
