# Generated by Django 3.1 on 2021-02-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0004_lead_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_date', models.DateField()),
                ('applicant_information', models.BooleanField(default=False, verbose_name='申込情報')),
                ('surety_screening', models.BooleanField(default=False, verbose_name='保証会社審査')),
                ('owner_screening', models.BooleanField(default=False, verbose_name='オーナー審査')),
                ('document_inform', models.BooleanField(default=False, verbose_name='必要書類の案内')),
                ('invoice_inform_applicant', models.BooleanField(default=False, verbose_name='入居者への請求書提示')),
                ('invoice_inform_agency', models.BooleanField(default=False, verbose_name='不動産業者への請求書提示')),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('contract_applicant', models.BooleanField(default=False, verbose_name='契約締結')),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('all_done', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead', verbose_name='Lead')),
            ],
        ),
    ]
