# Generated by Django 3.1.6 on 2021-03-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20210215_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyapplicationphase',
            name='all_done',
        ),
    ]
