# Generated by Django 3.1 on 2021-02-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
