# Generated by Django 3.1 on 2021-02-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_person'),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationPhase',
            new_name='PropertyApplicationPhase',
        ),
    ]
