# Generated by Django 3.1 on 2021-02-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_approach_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='approach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.approach'),
        ),
    ]
