# Generated by Django 3.1 on 2021-02-15 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210215_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.person'),
            preserve_default=False,
        ),
    ]
